# Generated by Django 4.0 on 2023-11-03 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_class', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('total_seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('booked_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_station', models.CharField(max_length=50)),
                ('to_station', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_class.trainclass')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
    ]
