# Generated by Django 4.0 on 2023-11-03 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train_class', '0001_initial'),
        ('trains', '0001_initial'),
        ('users', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='seatavailability',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_class.trainclass'),
        ),
        migrations.AddField(
            model_name='seatavailability',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketreservation',
            unique_together={('ticket_id', 'train', 'user', 'class_id')},
        ),
        migrations.AlterUniqueTogether(
            name='seatavailability',
            unique_together={('train', 'class_id', 'start_date')},
        ),
    ]
