# Generated by Django 4.0 on 2023-11-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_seatavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
