# Generated by Django 4.0 on 2023-11-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_table'),
        ('train_class', '0002_alter_trainclass_table'),
        ('reservations', '0005_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reservations.ticketreservation'),
        ),
        migrations.AlterField(
            model_name='seatavailability',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_seat_availability', to='train_class.trainclass'),
        ),
        migrations.AlterField(
            model_name='seatavailability',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_seat_availability', to='trains.train'),
        ),
    ]
