# Generated by Django 4.0 on 2023-11-20 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_passenger_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
