# Generated by Django 4.0 on 2023-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_remove_seatavailability_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatavailability',
            name='booked_seats',
        ),
    ]
