# Generated by Django 4.0 on 2023-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='train',
            index=models.Index(fields=['train_name'], name='train_train_n_704e7b_idx'),
        ),
    ]
