# Generated by Django 4.0 on 2023-11-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_alter_train_table'),
        ('stations', '0003_alter_route_unique_together_alter_route_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_station', to='stations.station'),
        ),
        migrations.AlterField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_train', to='trains.train'),
        ),
    ]
