# Generated by Django 4.0 on 2023-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_route_station_alter_route_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['station_name'], name='station_station_42cc05_idx'),
        ),
    ]
