# Generated by Django 4.0 on 2023-11-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainclass',
            table='train_class',
        ),
    ]
