# Generated by Django 4.0 on 2023-11-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amenities',
            table='amenities',
        ),
        migrations.AlterModelTable(
            name='amenitiesclass',
            table='amenities_class',
        ),
    ]
