# Generated by Django 4.0 on 2023-11-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_class', '0002_alter_trainclass_table'),
        ('amenities', '0002_alter_amenities_table_alter_amenitiesclass_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiesclass',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_amenities', to='train_class.trainclass'),
        ),
    ]
