# Generated by Django 4.0 on 2023-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dob_alter_user_gender_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
