# Generated by Django 4.0 on 2023-11-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useremail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useremail',
            table='user_email',
        ),
    ]
