# Generated by Django 4.0 on 2023-11-21 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useremail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that phone number already exists.'}, help_text='Required. Enter a valid phone number.', max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,10}$', 'Enter a valid phone number. It should contain only digits and an optional "+" at the beginning.')], verbose_name='phone number'),
        ),
    ]
