# Generated by Django 4.0 on 2023-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_no'], name='user_phone_n_a10e74_idx'),
        ),
    ]
